const data = [
    {
        "employer_name": "Radiansys, Inc.",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa7b14BwbMfVtwG8ssVhHLwcHVsfJvz53O2kb9&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Dice.com",
        "job_id": "eHixL_6NhtwAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.dice.com/job-detail/db4c8c7a-fdb7-448d-9830-e2d74b2e302b",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.5746,
        "job_description": "Python Developer (DAY one onsite)\n\nONLY TEXAS CANDIDATES\n\nDURATION: Contract\n\nJob Description:\n• Expertise in Core Python programming\n• Strong expertise in Capital Markets domain (Risk, financial pricing, valuations etc.)\n• Working knowledge and experience using threading limitation of Python and multi-process architecture and event driven programming\n• Experience in scheduling jobs or trigger events programmatically\n• Experience in Data Access and ORM tools like SQL Alchemy\n• Experience working with Pandas, NumPy and Regular Expressionism Python\n• Basic experience on Web services (Flask, Django), Web Apps (good to have)\n• Hands on experience with JIRA, Agile methodology, source code management - GIT, SVN etc.\n• Understanding of fundamental design principles for building a scalable application\n• Proficiency in implementing automated unit tests.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1684258072,
        "job_posted_at_datetime_utc": "2023-05-16T17:27:52.000Z",
        "job_city": "Texas City",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.383844,
        "job_longitude": -94.9027,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=eHixL_6NhtwAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-06-16T17:27:52.000Z",
        "job_offer_expiration_timestamp": 1686936472,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Data Access",
            "Django",
            "Flask",
            "GIT",
            "JIRA",
            "NumPy",
            "Pandas",
            "Python",
            "process architecture",
            "scheduling",
            "unit tests",
            "threading",
            "Capital Markets domain",
            "financial",
            "Risk",
            "valuations",
            "Web services",
            "Web Apps"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Strong expertise in Capital Markets domain (Risk, financial pricing, valuations etc.)",
                "Working knowledge and experience using threading limitation of Python and multi-process architecture and event driven programming",
                "Experience in scheduling jobs or trigger events programmatically",
                "Experience in Data Access and ORM tools like SQL Alchemy",
                "Experience working with Pandas, NumPy and Regular Expressionism Python",
                "Basic experience on Web services (Flask, Django), Web Apps (good to have)",
                "Hands on experience with JIRA, Agile methodology, source code management - GIT, SVN etc",
                "Understanding of fundamental design principles for building a scalable application",
                "Proficiency in implementing automated unit tests"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Insight Global",
        "employer_logo": "https://images.squarespace-cdn.com/content/5f7f984c3ca20d1d55b276f7/1619793549819-L54X3W9Z5RD277UPNH9S/IGLogoPublic.png?content-type=image%2Fpng",
        "employer_website": "http://www.insightglobal.com",
        "employer_company_type": "Staffing",
        "job_publisher": "LinkedIn",
        "job_id": "XKYtn9U4Q3MAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-at-insight-global-3609336000",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5532,
        "job_description": "Duration: 6 month contract with potential to extend or be hired as a full time associate.\n\nLocation: Remote during contract, will require relocation to Dallas, TX or Bentonville, AR if converted to a full time hire!\n\nInterview Process: 1 round with client\n\nRequirements\n• 2-5 years of Python Development experience\n• Airflow\n• DevOps experience with CI/CD pipeline",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1684272327,
        "job_posted_at_datetime_utc": "2023-05-16T21:25:27.000Z",
        "job_city": "Dallas",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.776665,
        "job_longitude": -96.79699,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=XKYtn9U4Q3MAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-06-15T21:25:27.000Z",
        "job_offer_expiration_timestamp": 1686864327,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 24,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 50,
        "job_max_salary": 58,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Qualifications": [
                "2-5 years of Python Development experience",
                "Airflow",
                "DevOps experience with CI/CD pipeline"
            ],
            "Responsibilities": [
                "Interview Process: 1 round with client"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Fintech",
        "employer_logo": "https://fintech.maharashtra.gov.in/cdn/about/Fintech-mumbai-og.png",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Learn4Good",
        "job_id": "nqQzDAMs5_sAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.learn4good.com/jobs/san-antonio/texas/info_technology/2333701649/e/",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.4005,
        "job_description": "Role:\n\nPython Developer\n\nLocation:\n\nIrving, TX (Day One onsite)\n\nType:\nFull Time\n\nRequired Skills:\n\n6+ years professional experience\n\nExperience building and managing microservice architecture-based application using Python (Python3 preferred)\n\nExperience with python packages like Num Py, pandas, flask, PYSpark, PYMongo, OS, logging, re, PYYaml\n\nExperience with swagger io module to expose API Experience in any of:\nOpen Shift, Kubernetes, NGINX, or Docker a plus.\n\nStrong RDBMS and Unix understanding with SQL and BASH shell scripting knowledge\nSDL\n2017",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1684195200,
        "job_posted_at_datetime_utc": "2023-05-16T00:00:00.000Z",
        "job_city": "San Antonio",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.42519,
        "job_longitude": -98.49459,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=nqQzDAMs5_sAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-11-15T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1700006400,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 72,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "6+ years professional experience",
                "Experience with python packages like Num Py, pandas, flask, PYSpark, PYMongo, OS, logging, re, PYYaml",
                "Experience with swagger io module to expose API Experience in any of:",
                "Strong RDBMS and Unix understanding with SQL and BASH shell scripting knowledge"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Extend Information Systems Inc",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Learn4Good",
        "job_id": "fPZDnX5AaHsAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.learn4good.com/jobs/irving/texas/info_technology/2335654651/e/",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.3996,
        "job_description": "Position: Python Developer Irving, TX Full-time\nHi Jobseeker ,\n\nI hope you are doing well!\n\nWe have an opportunity for Python Developer with one of our clients for Irving, TX (Day 1 onsite)\nPlease see the job details below and let me know if you would be interested in this role.\n\nIf interested, please send me a copy of your resume, contact details, availability, and a good time to connect with you.\n\nTitle\n\nPython Developer\n\nLocation:\n\nIrving, TX (Day 1 onsite) Terms:\nFulltime Job Details Technical/Functional Skills\nAdvanced Python knowledge with minimum 4-5 years relevant experience.\nKnowledge on REST API using python Flask, integration with Mongodb.\nBasic knowledge on unix commands.\nPriyanka tiwari Extend Information System Inc Phone:\nEmail: 44258 Mercure Circle, UNIT 102 A, Sterling VA, USA 20166\nSDL\n2017",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1684281600,
        "job_posted_at_datetime_utc": "2023-05-17T00:00:00.000Z",
        "job_city": "Irving",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.81402,
        "job_longitude": -96.94889,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=fPZDnX5AaHsAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-11-16T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1700092800,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 48,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Advanced Python knowledge with minimum 4-5 years relevant experience",
                "Knowledge on REST API using python Flask, integration with Mongodb"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "TEKsystems",
        "employer_logo": "https://www.teksystems.com/-/media/teksystems_com/Images/Logos/TEKsystems_logotype_RGB.png",
        "employer_website": "http://www.teksystems.com",
        "employer_company_type": "Staffing",
        "job_publisher": "TEKsystems Careers",
        "job_id": "kYsCl5qRCX0AAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://careers.teksystems.com/us/en/job/JP-003765275/Python-Developer",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.9677,
        "job_description": "Description:\n\n• Automation and re-engineering; business as usual processes converted to RPA, robotics to design, test, and deploy process automation to designated value streams.\n\n• Facilitates cross functional teams to user/developer cases and partners with business partners such as product management, strategy, technical leads, and systems operations support.\n\n• Designs, codes, tests, debug and document programs using Agile development practices.\n\n• Takes on new infrastructure requirements and developing infrastructure code.\n\n• Proactively identify troublesome trends as they develop; analyzes/predicts trends and develops a long-range plan designed to resolve problems and prevent them from recurring; maintains high service levels for the IT community.\n\n• Develops documentation for requirements, operational policies, and procedures, as well as documentation to deploy monitoring tools to the data center and application operations teams.\n\n• Designs complex system upgrades. Contributes to the analysis of business, application, and technical infrastructure requirements.\n\n• Champions and supports other team members by reducing churn and waste, removing blockers, escalating issues, and helping to mentor and grow team members.\n\n• Supports client and App Owners in resolving any Application/ Server level issues.\n\n• A strong business development professional with ServiceNow industry experience and the association of Wells Fargo CMDB asset management software\n\n• Proven team member who is goal-orientated with solid process engineering background (LEAN, Six Sigma.\n\nSkills:\n\nSplunk, Appd, UI/UX, Automation\n\nTop Skills Details:\n\nSplunk,Appd,UI/UX,Automation\n\nAdditional Skills & Qualifications:\n\nRequired Qualifications:\n\n• 5+ years of systems analysis experience\n\n• 5+ years of systems programming experience\n\n• 2+ years of experience in one or a combination of the following: Agile, Kanban, or Lean methodology\n\nDesired Qualifications:\n\n• Expert knowledge and understanding of technologies related to infrastructure engineering\n\n• Ability to identify, report, and solution problems in new and existing software in a team environment\n\n• Ability to identify and correct system capacity issues\n\n• Ability to help remediate tough technical support issues\n\n• In-depth technical solution knowledge, including installation, configuration, performance tuning, and problem solving\n\nSkills:\n\n• User Experience / Interface (UX/UI) Design\n\n• Facilitate ‘focus group’ to collect requirements, test, deploy automation\n\n• Exposure to these systems is a PLUS, AppDynamics,\n\n• Experienced IT Professional with a demonstrated history of working with enterprise environments. Exposure, Experience, and knowledge of WebLogic, WebSphere, JBoss, Kenna, Ansible.\n\nExperience Level:\n\nExpert Level\n\nAbout TEKsystems:\n\nWe're partners in transformation. We help clients activate ideas and solutions to take advantage of a new world of opportunity. We are a team of 80,000 strong, working with over 6,000 clients, including 80% of the Fortune 500, across North America, Europe and Asia. As an industry leader in Full-Stack Technology Services, Talent Services, and real-world application, we work with progressive leaders to drive change. That's the power of true partnership. TEKsystems is an Allegis Group company.\n\nThe company is an equal opportunity employer and will consider all applications without regards to race, sex, age, color, religion, national origin, veteran status, disability, sexual orientation, gender identity, genetic information or any characteristic protected by law.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1683721726,
        "job_posted_at_datetime_utc": "2023-05-10T12:28:46.000Z",
        "job_city": "Dallas",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.776665,
        "job_longitude": -96.79699,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=kYsCl5qRCX0AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Agile",
            "UI/UX",
            "Analysis",
            "Systems Programming",
            "Ansible",
            "agile development",
            "CMDB",
            "Splunk",
            "Kanban",
            "Automation",
            "Cross Functional",
            "ServiceNow",
            "Lean Methodology",
            "JBoss",
            "Engineering",
            "Infrastructure",
            "Process Engineering",
            "AppDynamics",
            "Documentation",
            "Technical Support",
            "Agile Development Practices",
            "infrastructure engineering",
            "Technology Services",
            "Transformation",
            "Asset Management Software",
            "System Upgrades",
            "Operations",
            "Business Development",
            "Six Sigma",
            "Design",
            "Python Developer",
            "Lead Python Developer",
            "Java Software Engineer",
            "Java Developer",
            "C# Developer",
            "Python Full Stack Developer",
            "Full-Stack Developer",
            "Senior Developer & Software Engineer .Net & Full Stack Developer & Full Stack Software Engineer .Net",
            "Big Data Developer &  Full Stack Developer",
            "Data Engineer & Python Developer"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "A strong business development professional with ServiceNow industry experience and the association of Wells Fargo CMDB asset management software",
                "Proven team member who is goal-orientated with solid process engineering background (LEAN, Six Sigma",
                "5+ years of systems analysis experience",
                "2+ years of experience in one or a combination of the following: Agile, Kanban, or Lean methodology",
                "User Experience / Interface (UX/UI) Design",
                "Facilitate ‘focus group’ to collect requirements, test, deploy automation",
                "Experienced IT Professional with a demonstrated history of working with enterprise environments",
                "Exposure, Experience, and knowledge of WebLogic, WebSphere, JBoss, Kenna, Ansible"
            ],
            "Responsibilities": [
                "Automation and re-engineering; business as usual processes converted to RPA, robotics to design, test, and deploy process automation to designated value streams",
                "Facilitates cross functional teams to user/developer cases and partners with business partners such as product management, strategy, technical leads, and systems operations support",
                "Designs, codes, tests, debug and document programs using Agile development practices",
                "Takes on new infrastructure requirements and developing infrastructure code",
                "Proactively identify troublesome trends as they develop; analyzes/predicts trends and develops a long-range plan designed to resolve problems and prevent them from recurring; maintains high service levels for the IT community",
                "Develops documentation for requirements, operational policies, and procedures, as well as documentation to deploy monitoring tools to the data center and application operations teams",
                "Designs complex system upgrades",
                "Contributes to the analysis of business, application, and technical infrastructure requirements",
                "Champions and supports other team members by reducing churn and waste, removing blockers, escalating issues, and helping to mentor and grow team members",
                "Supports client and App Owners in resolving any Application/ Server level issues"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Diverse Lynx",
        "employer_logo": "https://c.smartrecruiters.com/sr-company-images-prod/5525418ee4b08c20c6910cd4/default_social_logo/300x300?r=s3&_1534874151146",
        "employer_website": "http://www.diverselynx.com",
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "ToVYhrR3lZAAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-at-diverse-lynx-3569917972",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5644,
        "job_description": "Key Skills/Knowledge: Key responsibilities include:\n\nWill be responsible for technical analysis of the requirements, work estimates, detailed and technical design documentation, application code and associated documentation including documentation to fulfill audit requirement and ensuring that best practices and standard are adhered.\n\nGet involved in technical design, coding, testing, and implementation phases to meet business needs, solve business problems, and add value to the bottom line.\n\nSkills & Requirements\n\nGathering and evaluating user requirements, in collaboration with product managers and engineers.\n\nMinimum 5 - 8 years hands on experience on Python framework + Django (Python 3 strongly preferred)\n\nStrong Linux background\n\nExperience With a Relational Database (PostgreSQL Preferred)\n\nExperience with AWS configuration, setup and teardown\n\nHands on experience in Jira or VSTS.\n\nMust have working experience with GIT.\n\nShould have some basic knowledge of backend.\n\nParticipates in the coding, testing, implementation, and documentation of front-end development.\n\nMaintains and upgrades interface functionalities for specific requirements, and actively participates in code and project review as needed.\n\nParticipates in the business assessment and requirements analysis processes for the front-end development of graphical user interfaces.\n\nLeverages modern tools and techniques to develop clean, efficient, and reusable code.\n\nManaging Risk- Assessing and effectively managing all the risks associated with their business objectives and activities to ensure they adhere to and support Legend Framework.\n\nDiverse Lynx LLC is an Equal Employment Opportunity employer. All qualified applicants will receive due consideration for employment without any discrimination. All applicants will be evaluated solely on the basis of their ability, competence and their proven capability to perform the functions outlined in the corresponding role. We promote and support a diverse workforce across all levels in the company.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1681897194,
        "job_posted_at_datetime_utc": "2023-04-19T09:39:54.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=ToVYhrR3lZAAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-05-19T09:48:11.000Z",
        "job_offer_expiration_timestamp": 1684489691,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Strong Linux background",
                "Experience with AWS configuration, setup and teardown",
                "Hands on experience in Jira or VSTS",
                "Must have working experience with GIT",
                "Should have some basic knowledge of backend"
            ],
            "Responsibilities": [
                "Will be responsible for technical analysis of the requirements, work estimates, detailed and technical design documentation, application code and associated documentation including documentation to fulfill audit requirement and ensuring that best practices and standard are adhered",
                "Get involved in technical design, coding, testing, and implementation phases to meet business needs, solve business problems, and add value to the bottom line",
                "Participates in the coding, testing, implementation, and documentation of front-end development",
                "Maintains and upgrades interface functionalities for specific requirements, and actively participates in code and project review as needed",
                "Participates in the business assessment and requirements analysis processes for the front-end development of graphical user interfaces",
                "Leverages modern tools and techniques to develop clean, efficient, and reusable code",
                "Managing Risk- Assessing and effectively managing all the risks associated with their business objectives and activities to ensure they adhere to and support Legend Framework"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "extend information systems inc.",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Central Illinois Proud Jobs",
        "job_id": "b36aCwNT58QAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Looking for python Developer -Houston,TX- Full-time",
        "job_apply_link": "https://jobs.centralillinoisproud.com/jobs/looking-for-python-developer-houston-tx-full-time-houston-texas/1006367900-2/",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.553,
        "job_description": "Hi, Jobseekers,\n\nI hope you are doing well!\n\nWe have an opportunity for Python Developer with one of our clients for Houston, TX.\n\nPlease see the job details below and let me know if you would be interested in this role.\n\nIf interested, please send me a copy of your resume, contact details, availability, and a good time to connect with you.\n\nTitle: Python Developer\n\nLocation: Houston, TX\n\nTerms: Full-time\n\nJob Details\n\n5+ years' experience as Python developer.\n\nHands on experience in Django framework.\n\nStrong exposure and development experience using Time series data.\n\nRegression models (simple and more advanced techniques, linear and non-linear),\n\nTime series modelling\n\nStandard array of statistical software packages (Python, R, EViews, SAS)\n\nAzure fundamentals\n\nPower BI foundation level knowledge\n\nThanks & Regards\n\nMonika Singh\n\nExtend Information System Inc\n\nPhone:571-622-3980\n\nEmail: monika@\n\n44258 Mercure Circle, UNIT 102 A, Sterling VA, USA 20166",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1684094697,
        "job_posted_at_datetime_utc": "2023-05-14T20:04:57.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=b36aCwNT58QAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "5+ years' experience as Python developer",
                "Hands on experience in Django framework",
                "Strong exposure and development experience using Time series data",
                "Power BI foundation level knowledge"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Magnus Technology Solutions Inc",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Learn4Good",
        "job_id": "_97bZ_lRyoEAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer​/Entry Level",
        "job_apply_link": "https://www.learn4good.com/jobs/frisco/texas/software_development/2333864713/e/",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.4022,
        "job_description": "Job Description\n\nWe are seeking a Python Developer (Entry Level) to become an integral part of our team!\n\nYou will be responsible for creating and modifying computer application software or specialized utility programs.\n\nResponsibilities:\n• Analyze user needs and develop software solutions\n• Work with project manager or product owner to meet specification needs\n• Recommend software upgrades to optimize operational efficiency\n• Collaborate with other developers to design and optimize code\n• Create flowcharts and user guides for new and existing programs\n• Document all programming tasks and procedures\n• Perform routine software maintenance\n\nQualifications:\n• Previous experience in software development, computer engineering, or other related fields\n• Knowledge of Java, Python, or other programming languages\n• Familiarity with relational databases such as MySQL, Oracle, and SQL Server\n• Deadline and detail-oriented\n• Strong analytical and critical thinking skills Company Description Magnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA. We work on #Selenium, #, #, # #Dotnet, #java, #j2ee, #, #Angular, #React, #Python, #Dev Ops, #Salesforce, #Hadoop, #IOS, #Android, #RPA, #Mulesoft and any #Developer related #Technologies.\n\nCompany Description\n\nMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA. We work on #Selenium, #, #, # #Dotnet, #java, #j2ee, #, #Angular, #React, #Python, #Dev Ops, #Salesforce, #Hadoop, #IOS, #Android, #RPA, #Mulesoft and any #Developer related #Technologies.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1684195200,
        "job_posted_at_datetime_utc": "2023-05-16T00:00:00.000Z",
        "job_city": "Frisco",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 33.150673,
        "job_longitude": -96.82361,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=_97bZ_lRyoEAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-11-15T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1700006400,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Previous experience in software development, computer engineering, or other related fields",
                "Knowledge of Java, Python, or other programming languages",
                "Familiarity with relational databases such as MySQL, Oracle, and SQL Server",
                "Deadline and detail-oriented",
                "Strong analytical and critical thinking skills Company Description Magnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA"
            ],
            "Responsibilities": [
                "You will be responsible for creating and modifying computer application software or specialized utility programs",
                "Analyze user needs and develop software solutions",
                "Work with project manager or product owner to meet specification needs",
                "Recommend software upgrades to optimize operational efficiency",
                "Collaborate with other developers to design and optimize code",
                "Create flowcharts and user guides for new and existing programs",
                "Document all programming tasks and procedures",
                "Perform routine software maintenance"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Mphasis USA",
        "employer_logo": null,
        "employer_website": "http://mphasis.com",
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "FJjhCKEFMzsAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Full Time Python Developer Position",
        "job_apply_link": "https://www.linkedin.com/jobs/view/full-time-python-developer-position-at-mphasis-usa-3597897336",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5644,
        "job_description": "Title: Python Developer\n\nLocation: Houston, TX\n\nFull Time Position\n\nHybrid Role ( 3 days onsite in a week)\n\nSkills: Python Java\n\nExperience: 8+ Years\n\nJob Description:\n\nMigrate existing jobs from Python/Bob/Athena to Java/Autosys Support strategic projects (datacenter migration, etc.) as needed.\n• Extensive Experience with at least one the Python frameworks (e.g. Django, Flask, Bottle)\n• Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)\n• At least 6+ years of relevant experience as a software developer\n• Skilled with Python, and JAVA\n• Prior experience working with Python scripting and integration",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1683670969,
        "job_posted_at_datetime_utc": "2023-05-09T22:22:49.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=FJjhCKEFMzsAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-06-08T22:22:49.000Z",
        "job_offer_expiration_timestamp": 1686262969,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 72,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Python (Programming Language)",
            "Software Development",
            "Java",
            "Scripting"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Experience: 8+ Years",
                "Extensive Experience with at least one the Python frameworks (e.g. Django, Flask, Bottle)",
                "Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)",
                "At least 6+ years of relevant experience as a software developer",
                "Skilled with Python, and JAVA",
                "Prior experience working with Python scripting and integration"
            ],
            "Responsibilities": [
                "Hybrid Role ( 3 days onsite in a week)",
                "Migrate existing jobs from Python/Bob/Athena to Java/Autosys Support strategic projects (datacenter migration, etc.)"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "CGI Technologies and Solutions, Inc.",
        "employer_logo": "https://cdn.comparably.com/27384651/l/43761_logo_cgi-technologies-and-solutions-inc.png",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Jobs | CGI",
        "job_id": "d9RP3oFT62AAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "AI / ML Python Developer",
        "job_apply_link": "https://cgi.jobs/plano-tx/ai-ml-python-developer/CF60FC53B3CC4995AB99D426313158E4/job/",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.4944,
        "job_description": "CGI Technologies and Solutions, Inc.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1684279389,
        "job_posted_at_datetime_utc": "2023-05-16T23:23:09.000Z",
        "job_city": "Plano",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 33.019844,
        "job_longitude": -96.69888,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=d9RP3oFT62AAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15111100",
        "job_onet_job_zone": "5"
    }
]

export default data;
